//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kmx
{
    [Serializable]
    public class GetSafetyZonesResponse : Message
    {
        public const string k_RosMessageName = "kmx_msgs/GetSafetyZones";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;
        //  読取り成功か
        public string message;
        //  失敗理由（DCS未読/未接続/未対応 等）
        public SafetyZonesMsg zones;

        public GetSafetyZonesResponse()
        {
            this.ok = false;
            this.message = "";
            this.zones = new SafetyZonesMsg();
        }

        public GetSafetyZonesResponse(bool ok, string message, SafetyZonesMsg zones)
        {
            this.ok = ok;
            this.message = message;
            this.zones = zones;
        }

        public static GetSafetyZonesResponse Deserialize(MessageDeserializer deserializer) => new GetSafetyZonesResponse(deserializer);

        private GetSafetyZonesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
            deserializer.Read(out this.message);
            this.zones = SafetyZonesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
            serializer.Write(this.message);
            serializer.Write(this.zones);
        }

        public override string ToString()
        {
            return "GetSafetyZonesResponse: " +
            "\nok: " + ok.ToString() +
            "\nmessage: " + message.ToString() +
            "\nzones: " + zones.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
