//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kmx
{
    [Serializable]
    public class GetSafetyZonesRequest : Message
    {
        public const string k_RosMessageName = "kmx_msgs/GetSafetyZones";
        public override string RosMessageName => k_RosMessageName;

        //  「DCS再読込」ボタン＝オンデマンドで DCS 安全ゾーンを取得。DCS_ZONE_ROS2_LIVE_SPEC.md §4。
        public string robot_id;
        //  "" =既定

        public GetSafetyZonesRequest()
        {
            this.robot_id = "";
        }

        public GetSafetyZonesRequest(string robot_id)
        {
            this.robot_id = robot_id;
        }

        public static GetSafetyZonesRequest Deserialize(MessageDeserializer deserializer) => new GetSafetyZonesRequest(deserializer);

        private GetSafetyZonesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
        }

        public override string ToString()
        {
            return "GetSafetyZonesRequest: " +
            "\nrobot_id: " + robot_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
