//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kmx
{
    [Serializable]
    public class ObstaclesMsg : Message
    {
        public const string k_RosMessageName = "kmx_msgs/Obstacles";
        public override string RosMessageName => k_RosMessageName;

        //  kmx_msgs/Obstacles
        //  Unity → ROS2：ロボット周辺の障害物プリミティブ群。ROS2側で CollisionObject 化して planning scene へ。
        public string frame_id;
        //  通常 "base_link"（items の pose の基準フレーム）
        public ObstaclePrimitiveMsg[] items;

        public ObstaclesMsg()
        {
            this.frame_id = "";
            this.items = new ObstaclePrimitiveMsg[0];
        }

        public ObstaclesMsg(string frame_id, ObstaclePrimitiveMsg[] items)
        {
            this.frame_id = frame_id;
            this.items = items;
        }

        public static ObstaclesMsg Deserialize(MessageDeserializer deserializer) => new ObstaclesMsg(deserializer);

        private ObstaclesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame_id);
            deserializer.Read(out this.items, ObstaclePrimitiveMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_id);
            serializer.WriteLength(this.items);
            serializer.Write(this.items);
        }

        public override string ToString()
        {
            return "ObstaclesMsg: " +
            "\nframe_id: " + frame_id.ToString() +
            "\nitems: " + System.String.Join(", ", items.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
