//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kmx
{
    [Serializable]
    public class ObstaclePrimitiveMsg : Message
    {
        public const string k_RosMessageName = "kmx_msgs/ObstaclePrimitive";
        public override string RosMessageName => k_RosMessageName;

        //  kmx_msgs/ObstaclePrimitive
        //  1つの障害物プリミティブ。ロボット基部(base_link)相対・メートル・ROS(右手Z-up)系。
        public string id;
        //  一意ID（Unityオブジェクト名+InstanceID など）
        public byte type;
        //  1=BOX, 2=SPHERE, 3=CYLINDER（shape_msgs/SolidPrimitive 準拠）
        public double[] dimensions;
        //  BOX:[x,y,z] / SPHERE:[radius] / CYLINDER:[height,radius]
        public Geometry.PoseMsg pose;
        //  base_link 相対の姿勢

        public ObstaclePrimitiveMsg()
        {
            this.id = "";
            this.type = 0;
            this.dimensions = new double[0];
            this.pose = new Geometry.PoseMsg();
        }

        public ObstaclePrimitiveMsg(string id, byte type, double[] dimensions, Geometry.PoseMsg pose)
        {
            this.id = id;
            this.type = type;
            this.dimensions = dimensions;
            this.pose = pose;
        }

        public static ObstaclePrimitiveMsg Deserialize(MessageDeserializer deserializer) => new ObstaclePrimitiveMsg(deserializer);

        private ObstaclePrimitiveMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.type);
            deserializer.Read(out this.dimensions, sizeof(double), deserializer.ReadLength());
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.type);
            serializer.WriteLength(this.dimensions);
            serializer.Write(this.dimensions);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "ObstaclePrimitiveMsg: " +
            "\nid: " + id.ToString() +
            "\ntype: " + type.ToString() +
            "\ndimensions: " + System.String.Join(", ", dimensions.ToList()) +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
