//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kmx
{
    [Serializable]
    public class PlanRequestMsg : Message
    {
        public const string k_RosMessageName = "kmx_msgs/PlanRequest";
        public override string RosMessageName => k_RosMessageName;

        //  kmx_msgs/PlanRequest
        //  Unity → ROS2：始点/終点（関節角・度）で関節空間の経路生成を要求する。
        //  単位は他の kmx トピックと同じく「度」。ROS2ノード側で必要に応じ rad へ変換する。
        public string[] names;
        //  関節名。例 ["J1","J2","J3","J4","J5","J6"]。空なら受信側の既定順。
        public double[] start;
        //  始点 関節角（度）
        public double[] goal;
        //  終点 関節角（度）

        public PlanRequestMsg()
        {
            this.names = new string[0];
            this.start = new double[0];
            this.goal = new double[0];
        }

        public PlanRequestMsg(string[] names, double[] start, double[] goal)
        {
            this.names = names;
            this.start = start;
            this.goal = goal;
        }

        public static PlanRequestMsg Deserialize(MessageDeserializer deserializer) => new PlanRequestMsg(deserializer);

        private PlanRequestMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.start, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.goal, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.WriteLength(this.start);
            serializer.Write(this.start);
            serializer.WriteLength(this.goal);
            serializer.Write(this.goal);
        }

        public override string ToString()
        {
            return "PlanRequestMsg: " +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\nstart: " + System.String.Join(", ", start.ToList()) +
            "\ngoal: " + System.String.Join(", ", goal.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
