//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kmx
{
    [Serializable]
    public class SafetyZoneMsg : Message
    {
        public const string k_RosMessageName = "kmx_msgs/SafetyZone";
        public override string RosMessageName => k_RosMessageName;

        //  DCS(Dual Check Safety) CPC の1ゾーン（$DCSS_CPC[i] 由来）。
        //  robot World/base フレーム・単位 mm（KMX 側で ×0.001・軸写像）。DCS_ZONE_ROS2_LIVE_SPEC.md §4。
        public string id;
        //  例 "CPC1" or $COMMENT（"KMX_TEST"）。ゾーン識別
        public bool enabled;
        //  $ENABLE（1=有効）
        public bool inside_allowed;
        //  true=内側が安全域 / false=内側が進入禁止(keep-out)。$MODE から変換
        public double[] min_mm;
        //  [X1,Y1,Z1] 下限（$X[1],$Y[1],$Z1）
        public double[] max_mm;
        //  [X2,Y2,Z2] 上限（$X[2],$Y[2],$Z2）

        public SafetyZoneMsg()
        {
            this.id = "";
            this.enabled = false;
            this.inside_allowed = false;
            this.min_mm = new double[3];
            this.max_mm = new double[3];
        }

        public SafetyZoneMsg(string id, bool enabled, bool inside_allowed, double[] min_mm, double[] max_mm)
        {
            this.id = id;
            this.enabled = enabled;
            this.inside_allowed = inside_allowed;
            this.min_mm = min_mm;
            this.max_mm = max_mm;
        }

        public static SafetyZoneMsg Deserialize(MessageDeserializer deserializer) => new SafetyZoneMsg(deserializer);

        private SafetyZoneMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.enabled);
            deserializer.Read(out this.inside_allowed);
            deserializer.Read(out this.min_mm, sizeof(double), 3);
            deserializer.Read(out this.max_mm, sizeof(double), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.enabled);
            serializer.Write(this.inside_allowed);
            serializer.Write(this.min_mm);
            serializer.Write(this.max_mm);
        }

        public override string ToString()
        {
            return "SafetyZoneMsg: " +
            "\nid: " + id.ToString() +
            "\nenabled: " + enabled.ToString() +
            "\ninside_allowed: " + inside_allowed.ToString() +
            "\nmin_mm: " + System.String.Join(", ", min_mm.ToList()) +
            "\nmax_mm: " + System.String.Join(", ", max_mm.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
