//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kmx
{
    [Serializable]
    public class SafetyZonesMsg : Message
    {
        public const string k_RosMessageName = "kmx_msgs/SafetyZones";
        public override string RosMessageName => k_RosMessageName;

        //  DCS 安全ゾーン一覧（latched topic /kmx/safety_zones 用）。DCS_ZONE_ROS2_LIVE_SPEC.md §4。
        public string robot_id;
        //  対象ロボ（"" =既定/単機）。Ros2Info robots と対応
        public string frame;
        //  通常 "world"（UF0）
        public string unit;
        //  "mm"
        public SafetyZoneMsg[] zones;

        public SafetyZonesMsg()
        {
            this.robot_id = "";
            this.frame = "";
            this.unit = "";
            this.zones = new SafetyZoneMsg[0];
        }

        public SafetyZonesMsg(string robot_id, string frame, string unit, SafetyZoneMsg[] zones)
        {
            this.robot_id = robot_id;
            this.frame = frame;
            this.unit = unit;
            this.zones = zones;
        }

        public static SafetyZonesMsg Deserialize(MessageDeserializer deserializer) => new SafetyZonesMsg(deserializer);

        private SafetyZonesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.frame);
            deserializer.Read(out this.unit);
            deserializer.Read(out this.zones, SafetyZoneMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.robot_id);
            serializer.Write(this.frame);
            serializer.Write(this.unit);
            serializer.WriteLength(this.zones);
            serializer.Write(this.zones);
        }

        public override string ToString()
        {
            return "SafetyZonesMsg: " +
            "\nrobot_id: " + robot_id.ToString() +
            "\nframe: " + frame.ToString() +
            "\nunit: " + unit.ToString() +
            "\nzones: " + System.String.Join(", ", zones.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
