//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Kmx
{
    [Serializable]
    public class TagArrayMsg : Message
    {
        public const string k_RosMessageName = "kmx_msgs/TagArray";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public string[] names;
        public double[] values;

        public TagArrayMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.names = new string[0];
            this.values = new double[0];
        }

        public TagArrayMsg(BuiltinInterfaces.TimeMsg stamp, string[] names, double[] values)
        {
            this.stamp = stamp;
            this.names = names;
            this.values = values;
        }

        public static TagArrayMsg Deserialize(MessageDeserializer deserializer) => new TagArrayMsg(deserializer);

        private TagArrayMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.names, deserializer.ReadLength());
            deserializer.Read(out this.values, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
            serializer.WriteLength(this.values);
            serializer.Write(this.values);
        }

        public override string ToString()
        {
            return "TagArrayMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nnames: " + System.String.Join(", ", names.ToList()) +
            "\nvalues: " + System.String.Join(", ", values.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
